server:
  port: 8761

spring:
  application:
    name: service-registry

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: service-registry
    version: 1.0.0
    description: Eureka Server for Code Collaboration Platform

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false