CREATE DATABASE IF NOT EXISTS authdb;
CREATE DATABASE IF NOT EXISTS projectdb;
CREATE DATABASE IF NOT EXISTS filedb;
CREATE DATABASE IF NOT EXISTS collabdb;
CREATE DATABASE IF NOT EXISTS commentdb;
CREATE DATABASE IF NOT EXISTS executiondb;
CREATE DATABASE IF NOT EXISTS versiondb;
CREATE DATABASE IF NOT EXISTS notificationdb;

-- Grant privileges (MySQL 8 syntax)
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
FLUSH PRIVILEGES;
